### ISSUE TITLE
A request for help with a question about “base_function”

### ISSUE THREAD

**Issue by No-laine** [1098994933/Fatigue-life-prediction-of-aluminum-alloy#1]
Hello! Excuse me, I encountered some bugs when running the file, “Paper_Code-Copy1.ipynb”. The problem is that there is no modules “base_function”. Could you please provide the document “base.py” with me? Thank you!

**Comment by No-laine** [comment]
> 你好！请问，我在运行文件“Paper_Code-Copy1.ipynb”时遇到了一些错误。问题是没有模块“base_function”。你能提供文件“base.py”给我吗？谢谢！

**Comment by chao-su** [comment]
您好！同样的问题，怎么解决呢？是少传了一个模块吗？

**Comment by 1098994933** [comment]
Sorry for my mistakes. The module base_function was uploaded.
